<?php

namespace App\Support;

class VisualEditorCssScope
{
    /**
     * Scope GrapesJS generated CSS to the visual editor content wrapper.
     *
     * This prevents generic selectors generated by the visual editor, such as
     * body, header, footer, .container or div, from leaking into the public site
     * layout outside the page content area.
     */
    public static function scope(?string $css, string $scope = '.page-visual-content'): string
    {
        $css = trim((string) $css);

        if ($css === '') {
            return '';
        }

        return self::scopeCssBlock($css, $scope);
    }

    private static function scopeCssBlock(string $css, string $scope): string
    {
        $out = '';
        $len = strlen($css);
        $i = 0;

        while ($i < $len) {
            $nextOpen = strpos($css, '{', $i);

            if ($nextOpen === false) {
                $out .= substr($css, $i);
                break;
            }

            $selector = substr($css, $i, $nextOpen - $i);
            $blockEnd = self::findMatchingBrace($css, $nextOpen);

            if ($blockEnd === null) {
                $out .= substr($css, $i);
                break;
            }

            $body = substr($css, $nextOpen + 1, $blockEnd - $nextOpen - 1);
            $trimmedSelector = trim($selector);

            if ($trimmedSelector === '') {
                $out .= $selector . '{' . $body . '}';
                $i = $blockEnd + 1;
                continue;
            }

            if (str_starts_with($trimmedSelector, '@')) {
                $out .= self::scopeAtRule($trimmedSelector, $body, $scope);
            } else {
                $out .= self::scopeSelectorList($selector, $scope) . '{' . $body . '}';
            }

            $i = $blockEnd + 1;
        }

        return $out;
    }

    private static function scopeAtRule(string $selector, string $body, string $scope): string
    {
        $lower = strtolower($selector);

        if (str_starts_with($lower, '@media') || str_starts_with($lower, '@supports') || str_starts_with($lower, '@container')) {
            return $selector . '{' . self::scopeCssBlock($body, $scope) . '}';
        }

        // Keep keyframes, font-face, page and similar at-rules untouched.
        return $selector . '{' . $body . '}';
    }

    private static function scopeSelectorList(string $selectorList, string $scope): string
    {
        $selectors = self::splitSelectorList($selectorList);
        $scoped = [];

        foreach ($selectors as $selector) {
            $selector = trim($selector);

            if ($selector === '') {
                continue;
            }

            $scoped[] = self::scopeSelector($selector, $scope);
        }

        return implode(', ', $scoped);
    }

    private static function scopeSelector(string $selector, string $scope): string
    {
        $normalized = preg_replace('/\s+/', ' ', trim($selector));
        $lower = strtolower($normalized);

        if ($lower === $scope || str_starts_with($lower, strtolower($scope) . ' ')) {
            return $normalized;
        }

        // Global document selectors must become the content wrapper itself.
        if (in_array($lower, ['html', 'body', ':root', 'html body', 'body.page', 'body.page-template'], true)) {
            return $scope;
        }

        // The universal selector should not affect the entire public layout.
        if ($lower === '*') {
            return $scope . ' *';
        }

        // If GrapesJS generates a selector against the document body with children,
        // strip the global part and scope the remaining selector.
        foreach (['body ', 'html ', ':root '] as $globalPrefix) {
            if (str_starts_with($lower, $globalPrefix)) {
                $withoutGlobal = trim(substr($normalized, strlen($globalPrefix)));
                return $withoutGlobal === '' ? $scope : $scope . ' ' . $withoutGlobal;
            }
        }

        // Header/footer/nav/main are public layout elements in this CMS. If the user
        // really needs those tags inside the editor content, this still works because
        // the selector becomes scoped to page content only.
        return $scope . ' ' . $normalized;
    }

    private static function splitSelectorList(string $selectorList): array
    {
        $selectors = [];
        $buffer = '';
        $depth = 0;
        $quote = null;
        $len = strlen($selectorList);

        for ($i = 0; $i < $len; $i++) {
            $char = $selectorList[$i];

            if ($quote !== null) {
                $buffer .= $char;

                if ($char === $quote && ($i === 0 || $selectorList[$i - 1] !== '\\')) {
                    $quote = null;
                }

                continue;
            }

            if ($char === '"' || $char === "'") {
                $quote = $char;
                $buffer .= $char;
                continue;
            }

            if ($char === '(' || $char === '[') {
                $depth++;
                $buffer .= $char;
                continue;
            }

            if (($char === ')' || $char === ']') && $depth > 0) {
                $depth--;
                $buffer .= $char;
                continue;
            }

            if ($char === ',' && $depth === 0) {
                $selectors[] = $buffer;
                $buffer = '';
                continue;
            }

            $buffer .= $char;
        }

        if (trim($buffer) !== '') {
            $selectors[] = $buffer;
        }

        return $selectors;
    }

    private static function findMatchingBrace(string $css, int $openPos): ?int
    {
        $depth = 0;
        $quote = null;
        $len = strlen($css);

        for ($i = $openPos; $i < $len; $i++) {
            $char = $css[$i];

            if ($quote !== null) {
                if ($char === $quote && ($i === 0 || $css[$i - 1] !== '\\')) {
                    $quote = null;
                }

                continue;
            }

            if ($char === '"' || $char === "'") {
                $quote = $char;
                continue;
            }

            if ($char === '{') {
                $depth++;
                continue;
            }

            if ($char === '}') {
                $depth--;

                if ($depth === 0) {
                    return $i;
                }
            }
        }

        return null;
    }
}
